name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Проверка линтером
        run: |
          npm ci editorconfig-checker
          config=.editorconfig
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [ $changed_file == $config ]
            then
              echo "Проверка для всех файлов"
              editorconfig-checker
              break
            else
              echo "Проверка для ${changed_file}"
              editorconfig-checker ${changed_file}
            fi
          done
