name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Проверка форматирования
        uses: zbeekman/EditorConfig-Action@v1.1.0
