name: Frontmatter Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*/index.md'
      - name: Проверка линтером
        run: |
          npx yaml-cat -f json (css|html|js|tools)/**/index.md -o result.json
          node .github/scripts/frontmatter.js

