name: Link Checker in PR

on:
  pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.md'
      - name: Проверка ссылок в PR
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: ${{ steps.files.outputs.all }}
          markdown: true
          linksToSkip: "https://codepen.io/."
