name: Link Checker

on:
  pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          concurrency: 1
          markdown: true
          linksToSkip: "[/](css|content|html|js|tools)[/]."
