name: Link Checker

on:
  schedule:
    - cron:  '0 6 * * 5'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Проверка ссылок
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          markdown: true
          linksToSkip: "https://codepen.io/."
