name: Deploy Platform With Content

on:
  push:
    branches:
      - service/actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Загрузка платформы с контентом на Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}