name: YaSpeller

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Проверка правописания
        run: |
          config=.yaspeller.json
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [ $changed_file == $config ]
            then
              echo "Проверка для всех файлов"
              npx yaspeller **/*.{md,html}
              break
            else
              echo "Проверка для ${changed_file}"
              npx yaspeller ${changed_file}
            fi
          done
