name: YaSpeller

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Проверка правописания
        run: npx yaspeller {html,css,js,tools}/**/*.md
      - name: Сортировка словаря исключений
        run: node .github/scripts/sort.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Сортирует словарь исключений
          file_pattern: .yaspeller.json
          commit_user_name: Doka Dog
          commit_user_email: feedback@y-doka.site
          commit_author: Doka Dog <feedback@y-doka.site>
