name: YaSpeller All

on:
  push:
    branches:
      - fix/actions

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Yaspeller Action
        uses: heytitle/github-action-yaspeller/v0.0.7
        with:
          ext: "*.{md,html}"
